name: Lint Code Base & Build Utils

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies
      run: |
        poetry install

    - name: Run isort
      run: |
        poetry run isort .
      continue-on-error: true

    - name: Run black
      run: |
        poetry run black .
      continue-on-error: true

    - name: Run flake8
      run: |
        poetry run flake8 .
      continue-on-error: true

    - name: Run pylint
      run: |
        poetry run find . -name "*.py" | xargs pylint
      continue-on-error: true

    - name: Archive Lint Results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: lint-results
        path: |
          .flake8.log
          .pylint.log
  
  build-and-publish:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"
    
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry install --only main

    - name: Build the package
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry build

    - name: Publish to PyPI
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}
